### ISSUE TITLE
Issues with Upcoming 0.91 of HA

### ISSUE THREAD

**Issue by aidbish** [custom-components/sensor.kodi_recently_added#3]
HI
I have been testing the latest beta of HA and noticed on that this custom component fails to load

Thought i would bring to attention to be ready for next release.  
Version of sensor: 2.0.0
Tried on beta b0, b1, b2 and b3 of ha0.91

Error loading custom_components.kodi_recently_added.sensor. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/loader.py", line 183, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/kodi_recently_added/sensor.py", line 7, in <module>
    from homeassistant.components.media_player.kodi import (
ModuleNotFoundError: No module named 'homeassistant.components.media_player.kodi'
2019-03-30 02:59:00 ERROR (MainThread) [homeassistant.loader] Unable to find platform kodi_recently_added.

**Comment by dedors** [comment]
0.91 is live now and I am experience exaclty that problem.

**Comment by aidbish** [comment]
edit the custome component and change the line (7)
from

from homeassistant.components.media_player.kodi import (

to

from homeassistant.components.kodi.media_player import (

save and restart HA.

**Comment by boralyl** [comment]
Just upgraded this morning and saw the error, I'll get a fix released.

**Comment by boralyl** [comment]
Fixed in https://github.com/custom-components/sensor.kodi_recently_added/commit/75224a8de752f1ddb4ba354a88679c885ed00a62 0.2.2
